# Generated by Django 3.2.9 on 2021-12-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=15)),
                ('web_browser', models.CharField(max_length=50)),
                ('device', models.CharField(choices=[('pc', 'Pc'), ('MOBILE', 'Mobile'), ('TABLET', 'Tablet')], max_length=6)),
                ('device_os', models.CharField(max_length=30)),
                ('country_code', models.CharField(default='XX', max_length=2)),
                ('country_name', models.CharField(default='UNKNOWN', max_length=100)),
                ('shortened_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.shortenedurls')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
