# Generated by Django 3.2.9 on 2021-11-30 12:46

from django.db import migrations, models
import django.db.models.deletion
import shortener.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('industry', models.CharField(choices=[('personal', 'Personal'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('it', 'It'), ('others', 'Others')], default='others', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShortenedUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=50)),
                ('target_url', models.CharField(max_length=2000)),
                ('shortened_url', models.CharField(default=shortener.models.ShortenedUrls.rand_string, max_length=6)),
                ('create_via', models.CharField(choices=[('web', 'Website'), ('telegram', 'Telegram')], default='web', max_length=8)),
                ('expired_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shortener.categories')),
            ],
        ),
    ]
