# Generated by Django 3.2.9 on 2021-12-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurls',
            name='click',
            field=models.BigIntegerField(default=0),
        ),
    ]
