# Generated by Django 3.2.9 on 2021-12-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_shortenedurls_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shortenedurls',
            index=models.Index(fields=['prefix', 'shortened_url'], name='shortener_s_prefix_bbcd1e_idx'),
        ),
    ]
