# Generated by Django 3.2.9 on 2021-12-05 04:45

from django.db import migrations, models
import shortener.models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_shortenedurls_shortener_s_prefix_bbcd1e_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurls',
            name='prefix',
            field=models.CharField(default=shortener.models.ShortenedUrls.rand_letter, max_length=50),
        ),
    ]
